### ISSUE TITLE
nice theme

### ISSUE THREAD

**Issue by vardenixxxas** [liquidsquid1/catppuccin-lb#1]
too sad i dont see files

**Comment by DataM0del** [comment]
maybe because he hasn't pushed the files yet???

**Comment by vardenixxxas** [comment]
> maybe because he hasn't pushed the files yet???
no i think he is removing the skidded code

**Comment by jesterwoohoo** [comment]
> > maybe because he hasn't pushed the files yet???
> 
> no i think he is removing the skidded code
he skidded this from nightx too i think
also i had this theme prerelease its like 50mb unzipped

**Comment by vardenixxxas** [comment]
50mb? is he making a whole ass client?

**Comment by jesterwoohoo** [comment]
> 50mb? is he making a whole ass client?


you mean whole ass rat because he is nightx dev

**Comment by liquidsquid1** [comment]
> > > maybe because he hasn't pushed the files yet???
> > 
> > 
> > no i think he is removing the skidded code
> 
> he skidded this from nightx too i think also i had this theme prerelease its like 50mb unzipped

It was 15mb, and I have optimised it down to about 2mb.

**Comment by jesterwoohoo** [comment]
> > > > maybe because he hasn't pushed the files yet???
> > > 
> > > 
> > > no i think he is removing the skidded code
> > 
> > 
> > he skidded this from nightx too i think also i had this theme prerelease its like 50mb unzipped
> 
> It was 15mb, and I have optimised it down to about 2mb.

really sir when i had it zipped it was 20 mb

**Comment by liquidsquid1** [comment]
> > > > > maybe because he hasn't pushed the files yet???
> > > > 
> > > > 
> > > > no i think he is removing the skidded code
> > > 
> > > 
> > > he skidded this from nightx too i think also i had this theme prerelease its like 50mb unzipped
> > 
> > 
> > It was 15mb, and I have optimised it down to about 2mb.
> 
> really sir when i had it zipped it was 20 mb

There is nothing I can do about this.

**Comment by jesterwoohoo** [comment]
> > > > > > maybe because he hasn't pushed the files yet???
> > > > > 
> > > > > 
> > > > > no i think he is removing the skidded code
> > > > 
> > > > 
> > > > he skidded this from nightx too i think also i had this theme prerelease its like 50mb unzipped
> > > 
> > > 
> > > It was 15mb, and I have optimised it down to about 2mb.
> > 
> > 
> > really sir when i had it zipped it was 20 mb
> 
> There is nothing I can do about this.


very well i shall report this to the rise authorities
